export const BOOKS_HAS_ERRORED = 'BOOKS_HAS_ERRORED';
export const BOOKS_IS_LOADING = 'BOOKS_IS_LOADING';
export const BOOKS_FETCH_DATA_SUCCESS = 'BOOKS_FETCH_DATA_SUCCESS';
export const BOOKS_SET_CURRENT_PAGE = 'BOOKS_SET_CURRENT_PAGE';