export const LOGIN_UPDATE_USERNAME_TEXT = 'LOGIN_UPDATE_USERNAME_TEXT';
export const LOGIN_UPDATE_PASSWORD_TEXT = 'LOGIN_UPDATE_PASSWORD_TEXT';
export const LOGIN_HAS_ERRORED = 'LOGIN_HAS_ERRORED';
export const LOGIN_IS_LOADING = 'LOGIN_IS_LOADING';
export const LOGIN_SET_TOKEN = 'LOGIN_SET_TOKEN';
export const LOGIN_SET_USER = 'LOGIN_SET_USER';