export const SIGNUP_UPDATE_FIRSTNAME_TEXT = 'SIGNUP_UPDATE_FIRSTNAME_TEXT';
export const SIGNUP_UPDATE_LASTNAME_TEXT = 'SIGNUP_UPDATE_LASTNAME_TEXT';
export const SIGNUP_UPDATE_LOGIN_TEXT = 'SIGNUP_UPDATE_LOGIN_TEXT';
export const SIGNUP_UPDATE_EMAIL_TEXT = 'SIGNUP_UPDATE_EMAIL_TEXT';
export const SIGNUP_UPDATE_PASSWORD_TEXT = 'SIGNUP_UPDATE_PASSWORD_TEXT';
export const SIGNUP_HAS_ERRORED = 'SIGNUP_HAS_ERRORED';
export const SIGNUP_IS_LOADING = 'SIGNUP_IS_LOADING';
export const SET_RESPONSE_TEXT = 'SET_RESPONSE_TEXT';